# Generated by Django 4.0.2 on 2022-04-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('detalhe', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
