# Generated by Django 4.0.2 on 2022-04-22 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0003_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='arquivo.topologia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='arquivo.estado')),
                ('assunto', models.CharField(max_length=100)),
                ('autor', models.CharField(blank=True, max_length=70, null=True)),
                ('numero_pagina', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('destinatario', models.CharField(blank=True, max_length=70, null=True)),
                ('departamentoDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='arquivo.departamento')),
                ('descricao', models.CharField(blank=True, max_length=670, null=True)),
                ('numeroProcesso', models.CharField(blank=True, max_length=20, null=True)),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('dataEntrada', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['assunto'],
            },
        ),
    ]
