# Generated by Django 3.2.4 on 2022-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0004_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='nnumeroIdentificacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='uploads/%Y/'),
        ),
    ]
