# Generated by Django 4.0.2 on 2022-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0006_rename_nnumeroidentificacao_arquivo_numeroidentificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/'),
        ),
    ]
