# Generated by Django 4.0.2 on 2022-05-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0007_alter_arquivo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='foto',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='fotos/'),
        ),
    ]
