# Generated by Django 4.0.2 on 2022-05-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0010_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='detalhe',
        ),
        migrations.AddField(
            model_name='resposta',
            name='msg',
            field=models.CharField(blank=True, max_length=790, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='solicitacao',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='arquivo.arquivo'),
        ),
    ]
