# Generated by Django 4.0.2 on 2022-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0011_remove_resposta_detalhe_resposta_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('detalhe', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
