# Generated by Django 4.0.2 on 2022-05-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0012_tiporesposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='resposta',
        ),
    ]
