# Generated by Django 4.0.2 on 2022-05-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0013_remove_resposta_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='tipoResposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='arquivo.tiporesposta'),
        ),
    ]
