# Generated by Django 4.0.2 on 2022-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0014_resposta_tiporesposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='solicitacao',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
