# Generated by Django 4.0.2 on 2022-05-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0015_alter_resposta_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
