# Generated by Django 4.0.2 on 2022-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0017_alter_resposta_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='msg',
            field=models.CharField(blank=True, max_length=10990, null=True),
        ),
    ]
