# Generated by Django 4.0.2 on 2022-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0003_utilizador_departamentodestino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previlegios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, default=' ', max_length=3, null=True)),
                ('descricao', models.CharField(blank=True, default=' ', max_length=190, null=True)),
            ],
        ),
    ]
